default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fl_clone_development
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "fl-clone-db" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { "5432" } %>

test:
  <<: *default
  database: fl_clone_test
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "fl-clone-db" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { "5432" } %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "fl_clone_production" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "fl-clone-db" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { "5432" } %>

